# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9a976b8511e0b39715e1cb376f79831a1dc4acc0e3b76f787c629de5cdfebff0daf2b1d984a826354bf5d67d1faaa28103d301ae4e3c3a25b786b649b20f430

test:
  secret_key_base: 5af3257d42b78f2049c770488cdcc88a02c8b0a8d64c76b0640d389c12f16adbf17312cb0538fad22e9e19a9e3abd399fc6ad06ecc9295b46bcc80dece9aab2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
